### ISSUE TITLE
StreamHats voting screen issue while using it with Town Of Us

### ISSUE THREAD

**Issue by ThatOneDevilWasTaken** [ramsyiq/StreamHats#2]
The hats are really great and amazing and I love every single one of them, but since the font is too big while using this pack and Town of Us, when the setting "See everyone's role as a ghost" is true, nothing shows, only big white names with black outline, sadly I can't find a fix for this issue and I don't want to delete the pack since I found an amazing combo I am planning to keep.

I hope in future versions it will be fixed.

**Comment by amsyarasyiq** [comment]
I've never tested this mod with other mods properly yet. So I think right now the only quick fix is to disable some of this mod's feature (which can cause the other mods to broken) if there's more than one mod is running..

I will pre-release the hotfix real quick, this issue will remains open.

**Comment by ThatOneDevilWasTaken** [comment]
Is it still supposed to say version 1.9.6 on the top left when you launch the game? because I tried one game with this and the issue is still there, I deleted the old files and redid the steps but with the version 1.9.7-pre.1 and it didn't work..

**Comment by amsyarasyiq** [comment]
> Is it still supposed to say version 1.9.6 on the top left when you launch the game? because I tried one game with this and the issue is still there, I deleted the old files and redid the steps but with the version 1.9.7-pre.1 and it didn't work..

oh sorry I forgot to change the mod version, the patch will still work btw

**Comment by ThatOneDevilWasTaken** [comment]
So do I need to download or do something different? Because just like I stated before the file you linked doesn't fix my issue

**Comment by amsyarasyiq** [comment]
umm, can you try this one? https://github.com/ramsyiq/StreamHats/releases/tag/v1.9.7-pre.2

**Comment by amsyarasyiq** [comment]
issue reopened due to major bug due to the patch

**Comment by amsyarasyiq** [comment]
closed as new mod detector is implemented on the latest version
